const kMovieList = {
  "Avatar",
  "Avengers: Endgame",
  "Titanic",
  "Star Wars: Episode VII - The Force Awakens",
  "Avengers: Infinity War",
  "Spider-Man: No Way Home",
  "Jurassic World",
  "The Lion King",
  "The Avengers",
  "Furious 7",
  "Frozen II",
  "Avengers: Age of Ultron",
  "Black Panther",
  "Harry Potter and the Deathly Hallows: Part 2",
  "Star Wars: Episode VIII - The Last Jedi",
  "Jurassic World: Fallen Kingdom",
  "Frozen",
  "Beauty and the Beast",
  "Incredibles 2",
  "The Fate of the Furious",
  "Iron Man 3",
  "Minions",
  "Captain America: Civil War",
  "Aquaman",
  "The Lord of the Rings: The Return of the King",
  "Spider-Man: Far from Home",
  "Captain Marvel",
  "Transformers: Dark of the Moon",
  "Skyfall",
  "Transformers: Age of Extinction",
  "Jurassic Park",
  "The Dark Knight Rises",
  "Joker",
  "Star Wars: Episode IX - The Rise of Skywalker",
  "Toy Story 4",
  "Toy Story 3",
  "Pirates of the Caribbean: Dead Man's Chest",
  "Rogue One: A Star Wars Story",
  "Aladdin",
  "Pirates of the Caribbean: On Stranger Tides",
  "Despicable Me 3",
  "Finding Dory",
  "Star Wars: Episode I - The Phantom Menace",
  "Alice in Wonderland",
  "Zootopia",
  "Harry Potter and the Sorcerer's Stone",
  "The Hobbit: An Unexpected Journey",
  "The Dark Knight",
  "Harry Potter and the Deathly Hallows: Part 1",
  "Despicable Me 2",
  "The Jungle Book",
  "Jumanji: Welcome to the Jungle",
  "The Hobbit: The Battle of the Five Armies",
  "Pirates of the Caribbean: At World's End",
  "The Hobbit: The Desolation of Smaug",
  "The Lord of the Rings: The Two Towers",
  "Harry Potter and the Order of the Phoenix",
  "Finding Nemo",
  "Harry Potter and the Half-Blood Prince",
  "Shrek 2",
  "Bohemian Rhapsody",
  "The Battle at Lake Changjin",
  "The Lord of the Rings: The Fellowship of the Ring",
  "Harry Potter and the Goblet of Fire",
  "Spider-Man 3",
  "Ice Age 3: Dawn of the Dinosaurs",
  "Spectre",
  "Spider-Man: Homecoming",
  "Harry Potter and the Chamber of Secrets",
  "Ice Age 4: Continental Drift",
  "The Secret Life of Pets",
  "Batman v Superman: Dawn of Justice",
  "Wolf Warrior 2",
  "Star Wars: Episode III - Revenge of the Sith",
  "The Hunger Games: Catching Fire",
  "Guardians of the Galaxy Vol. 2",
  "Inside Out",
  "Venom",
  "Thor: Ragnarok",
  "Inception",
  "Transformers: Revenge of the Fallen",
  "The Twilight Saga: Breaking Dawn - Part 2",
  "Spider-Man",
  "Wonder Woman",
  "Hi, Mom",
  "Independence Day",
  "Fantastic Beasts and Where to Find Them",
  "Shrek the Third",
  "Coco",
  "Jumanji: The Next Level",
  "Harry Potter and the Prisoner of Azkaban",
  "Pirates of the Caribbean: Dead Men Tell No Tales",
  "E.T. the Extra-Terrestrial",
  "Mission: Impossible - Fallout",
  "2012",
  "Indiana Jones and the Kingdom of the Crystal Skull",
  "Spider-Man 2",
  "Fast & Furious 6",
  "Deadpool 2",
  "Deadpool",
  "Star Wars",
  "No Time to Die",
  "Guardians of the Galaxy",
  "The Da Vinci Code",
  "Fast & Furious Presents: Hobbs & Shaw",
  "Maleficent",
  "The Amazing Spider-Man",
  "The Hunger Games: Mockingjay - Part 1",
  "Shrek Forever After",
  "Madagascar 3: Europe's Most Wanted",
  "Suicide Squad",
  "X-Men: Days of Future Past",
  "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
  "Monsters University",
  "The Matrix Reloaded",
  "Up",
  "Ne Zha",
  "F9: The Fast Saga",
  "Gravity",
  "The Batman",
  "Captain America: The Winter Soldier",
  "The Twilight Saga: Breaking Dawn - Part 1",
  "The Twilight Saga: New Moon",
  "Dawn of the Planet of the Apes",
  "Transformers",
  "The Amazing Spider-Man 2",
  "It",
  "Interstellar",
  "The Wandering Earth",
  "The Twilight Saga: Eclipse",
  "Mission: Impossible - Ghost Protocol",
  "The Hunger Games",
  "Detective Chinatown 3",
  "Mission: Impossible - Rogue Nation",
  "Forrest Gump",
  "Doctor Strange",
  "The Sixth Sense",
  "Man of Steel",
  "Ice Age 2: The Meltdown",
  "Kung Fu Panda 2",
  "The Hunger Games: Mockingjay - Part 2",
  "Justice League",
  "Big Hero 6",
  "Fantastic Beasts: The Crimes of Grindelwald",
  "Pirates of the Caribbean: The Curse of the Black Pearl",
  "Star Wars: Episode II - Attack of the Clones",
  "Thor: The Dark World",
  "Moana",
  "Sing",
  "Kung Fu Panda",
  "The Incredibles",
  "The Martian",
  "Hancock",
  "Water Gate Bridge",
  "Fast Five",
  "Men in Black 3",
  "Iron Man 2",
  "Ratatouille",
  "Ant-Man and the Wasp",
  "How to Train Your Dragon 2",
  "Logan",
  "The Lost World: Jurassic Park",
  "Casino Royale",
  "The Passion of the Christ",
  "Mamma Mia!",
  "Life of Pi",
  "Transformers: The Last Knight",
  "Madagascar: Escape 2 Africa",
  "War of the Worlds",
  "Tangled",
  "Quantum of Solace",
  "Men in Black",
  "The Croods",
  "The Hangover Part II",
  "Iron Man",
  "I Am Legend",
  "Ready Player One",
  "Monsters, Inc.",
  "Operation Red Sea",
  "Night at the Museum",
  "Fifty Shades of Grey",
  "Kong: Skull Island",
  "The Smurfs",
  "Cars 2",
  "King Kong",
  "Puss in Boots",
  "The Mermaid",
  "Armageddon",
  "The Day After Tomorrow",
  "Ted",
  "American Sniper",
  "Mission: Impossible II",
  "Detective Chinatown 2",
  "X-Men: Apocalypse",
  "Sherlock Holmes: A Game of Shadows",
  "Despicable Me",
  "Cinderella",
  "Madagascar",
  "World War Z",
  "Brave",
  "Star Wars: Episode V - The Empire Strikes Back",
  "The Simpsons Movie",
  "The Revenant",
  "The Meg",
  "Ralph Breaks the Internet: Wreck-It Ralph 2",
  "Hotel Transylvania 3: Summer Vacation",
  "The Boss Baby",
  "Dunkirk",
  "Godzilla",
  "How to Train Your Dragon: The Hidden World",
  "Sherlock Holmes",
  "Meet the Fockers",
  "WALL·E",
  "Kung Fu Panda 3",
  "Terminator 2: Judgment Day",
  "Ant-Man",
  "The Grinch",
  "Ghost",
  "Venom: Let There Be Carnage",
  "Rio 2",
  "Troy",
  "Toy Story 2",
  "How to Train Your Dragon",
  "Twister",
  "Oz the Great and Powerful",
  "Clash of the Titans",
  "Maleficent: Mistress of Evil",
  "War for the Planet of the Apes",
  "Shrek",
  "Mr. & Mrs. Smith",
  "Angels & Demons",
  "Teenage Mutant Ninja Turtles",
  "Bruce Almighty",
  "Rio",
  "Saving Private Ryan",
  "Rise of the Planet of the Apes",
  "Home Alone",
  "Hotel Transylvania 2",
  "Star Wars: Episode VI - Return of the Jedi",
  "Charlie and the Chocolate Factory",
  "Indiana Jones and the Last Crusade",
  "San Andreas",
  "It Chapter Two",
  "Jaws",
  "Wreck-It Ralph",
  "The Hangover",
  "The Lego Movie",
  "Godzilla vs. Kong",
  "Bumblebee",
  "Star Trek Into Darkness",
  "The Matrix",
  "Gladiator",
  "Pretty Woman",
  "Cars",
  "The Eight Hundred",
  "X-Men: The Last Stand",
  "National Treasure: Book of Secrets",
  "Lucy",
  "Mission: Impossible",
  "300",
  "Demon Slayer the Movie: Mugen Train",
  "The Last Samurai",
  "Dying to Survive",
  "Ocean's Eleven",
  "My People, My Country",
  "Thor",
  "Pearl Harbor",
  "La La Land",
  "Tarzan",
  "Men in Black II",
  "The Bourne Ultimatum",
  "The Mummy Returns",
  "Alvin and the Chipmunks: The Squeakquel",
  "Les Misérables",
  "The Exorcist",
  "Mrs. Doubtfire",
  "Terminator Genisys",
  "Warcraft",
  "The Greatest Showman",
  "A Star Is Born",
  "Pokémon Detective Pikachu",
  "Terminator 3: Rise of the Machines",
  "Shang-Chi and the Legend of the Ten Rings",
  "Die Another Day",
  "The Secret Life of Pets 2",
  "Cast Away",
  "Rampage",
  "The King's Speech",
  "The Matrix Revolutions",
  "The Intouchables",
  "Bad Boys for Life",
  "Django Unchained",
  "Dances with Wolves",
  "My People, My Homeland",
  "The Chronicles of Narnia: Prince Caspian",
  "Sex and the City",
  "The Captain",
  "The Mummy",
  "The Chronicles of Narnia: The Voyage of the Dawn Treader",
  "Jason Bourne",
  "The Wolverine",
  "Kingsman: The Secret Service",
  "Night at the Museum: Battle of the Smithsonian",
  "Batman",
  "The Bodyguard",
  "Pacific Rim",
  "Kingsman: The Golden Circle",
  "Ice Age 5: Collision Course",
  "Twilight",
  "Signs",
  "X2: X-Men United",
  "Alita: Battle Angel",
  "The Mummy: Tomb of the Dragon Emperor",
  "Prometheus",
  "Gone with the Wind",
  "Mamma Mia! Here We Go Again",
  "Eternals",
  "Dune",
  "TRON: Legacy",
  "Mission: Impossible III",
  "Snow White and the Huntsman",
  "Grease",
  "Sing 2",
  "Toy Story",
  "Solo: A Star Wars Story",
  "The Wolf of Wall Street",
  "Superman Returns",
  "Robin Hood: Prince of Thieves",
  "Indiana Jones and the Raiders of the Lost Ark",
  "Independence Day: Resurgence",
  "Live Free or Die Hard",
  "Monster Hunt",
  "Godzilla: King of the Monsters",
  "Home",
  "Star Trek",
  "1917",
  "Happy Feet",
  "Cars 3",
  "Back to the Future",
  "Ice Age",
  "Fifty Shades Darker",
  "Monsters vs. Aliens",
  "Black Widow",
  "True Lies",
  "Slumdog Millionaire",
  "Taken 2",
  "G.I. Joe: Retaliation",
  "Mad Max: Fury Road",
  "Spider-Man: Into the Spider-Verse",
  "Shark Tale",
  "Once Upon a Time... In Hollywood",
  "Uncharted",
  "What Women Want",
  "The Adventures of Tintin",
  "Batman Begins",
  "Penguins of Madagascar",
  "X-Men Origins: Wolverine",
  "The Golden Compass",
  "Fifty Shades Freed",
  "Hitch",
  "Terminator Salvation",
  "Captain America: The First Avenger",
  "Edge of Tomorrow",
  "There's Something About Mary",
  "Gone Girl",
  "The Fugitive",
  "Jurassic Park III",
  "My Big Fat Greek Wedding",
  "Hello Mr. Billionaire",
  "Die Hard with a Vengeance",
  "Shazam!",
  "The Nun",
  "Alvin and the Chipmunks",
  "Notting Hill",
  "Tenet",
  "A Bug's Life",
  "Night at the Museum: Secret of the Tomb",
  "Ocean's Twelve",
  "Planet of the Apes",
  "The Hangover Part III",
  "The World Is Not Enough",
  "Monster Hunt 2",
  "Fast & Furious",
  "Noah",
  "The Karate Kid",
  "Home Alone 2: Lost in New York",
  "Hotel Transylvania",
  "Minority Report",
  "Your Name.",
  "Top Gun",
  "The Legend of Tarzan",
  "American Beauty",
  "Spirited Away",
  "Apollo 13",
  "Rain Man",
  "The Great Gatsby",
  "Dumbo",
  "I, Robot",
  "Basic Instinct",
  "Murder on the Orient Express",
  "X-Men: First Class",
  "The Angry Birds Movie",
  "GoldenEye",
  "Catch Me If You Can",
  "Now You See Me",
  "Hannibal",
  "The Mask",
  "Peter Rabbit",
  "Speed",
  "Dinosaur",
  "Mary Poppins Returns",
  "Deep Impact",
  "The Lorax",
  "The Maze Runner",
  "The Smurfs 2",
  "National Treasure",
  "Rush Hour 2",
  "Trolls",
  "xXx: Return of Xander Cage",
  "Pocahontas",
  "How the Grinch Stole Christmas",
  "Star Trek Beyond",
  "Alvin and the Chipmunks: Chipwrecked",
  "Wanted",
  "The Flintstones",
  "A Quiet Place",
  "Enchanted",
  "Over the Hedge",
  "300: Rise of an Empire",
  "Batman Forever",
  "Prince of Persia: The Sands of Time",
  "The Curious Case of Benjamin Button",
  "Journey 2: The Mysterious Island",
  "The Rock",
  "The Great Wall",
  "Now You See Me 2",
  "Never Say Die",
  "Fantastic Four",
  "Indiana Jones and the Temple of Doom",
  "Tomorrow Never Dies",
  "Back to the Future Part II",
  "The Good Dinosaur",
  "Free Guy",
  "22 Jump Street",
  "Meet the Parents",
  "Who Framed Roger Rabbit",
  "Black Swan",
  "The Perfect Storm",
  "Crocodile Dundee",
  "Crazy Alien",
  "Se7en",
  "John Wick: Chapter 3 - Parabellum",
  "The Devil Wears Prada",
  "Taken 3",
  "The Hunchback of Notre Dame",
  "A Christmas Carol",
  "The SpongeBob Movie: Sponge Out of Water",
  "Schindler's List",
  "Megamind",
  "The Conjuring 2",
  "Green Book",
  "Lethal Weapon 3",
  "The Ugly Truth",
  "Robin Hood",
  "Inglourious Basterds",
  "101 Dalmatians",
  "The Conjuring",
  "Fatal Attraction",
  "Sonic the Hedgehog",
  "The Last Airbender",
  "The Proposal",
  "A Beautiful Mind",
  "Beverly Hills Cop",
  "The Polar Express",
  "Air Force One",
  "The Expendables 2",
  "Chicken Little",
  "As Good as It Gets",
  "Maze Runner: The Scorch Trials",
  "Resident Evil: The Final Chapter",
  "The Lego Batman Movie",
  "Austin Powers: The Spy Who Shagged Me",
  "Knives Out",
  "Ocean's Thirteen",
  "Little Fockers",
  "Bolt",
  "Ransom",
  "Runaway Bride",
  "The Blind Side",
  "The Ex-File 3: The Return of The Exes",
  "The Fault in Our Stars",
  "The Pursuit of Happyness",
  "Rise of the Guardians",
  "Close Encounters of the Third Kind",
  "Chicago",
  "Annabelle: Creation",
  "Wonder",
  "Skyscraper",
  "A Good Day to Die Hard",
  "Mulan",
  "Dangal",
  "Passengers",
  "Battleship",
  "Liar Liar",
  "G.I. Joe: The Rise of Cobra",
  "Wrath of the Titans",
  "Fantastic 4: Rise of the Silver Surfer",
  "Hook",
  "Superman",
  "Rocky IV",
  "Rambo: First Blood Part II",
  "Resident Evil: Afterlife",
  "Van Helsing",
  "Stuart Little",
  "Beverly Hills Cop II",
  "Alice Through the Looking Glass",
  "My Best Friend's Wedding",
  "Real Steel",
  "Horton Hears a Who!",
  "Ocean's Eight",
  "A Quiet Place Part II",
  "The Divergent Series: Insurgent",
  "Look Who's Talking",
  "Austin Powers in Goldmember",
  "Ghostbusters",
  "Miss Peregrine's Home for Peculiar Children",
  "X-Men",
  "Ferdinand",
  "Shutter Island",
  "Doctor Dolittle",
  "Bee Movie",
  "Salt",
  "G-Force",
  "The Departed",
  "What Lies Beneath",
  "Pacific Rim: Uprising",
  "The Bourne Supremacy",
  "Sex and the City 2",
  "Shakespeare in Love",
  "Divergent",
  "Coming to America",
  "Wedding Crashers",
  "Bridesmaids",
  "Maze Runner: The Death Cure",
  "Casper",
  "American Pie 2",
  "Pitch Perfect 2",
  "The Green Mile",
  "Oblivion",
  "Elysium",
  "Lethal Weapon 4",
  "John Carter",
  "Turbo",
  "Paddington",
  "Bridget Jones's Diary",
  "The Tourist",
  "Split",
  "Scary Movie",
  "xXx",
  "The Bourne Legacy",
  "Mr. Peabody & Sherman",
  "Scooby-Doo",
  "Lincoln",
  "Lara Croft: Tomb Raider",
  "Tomb Raider",
  "The Expendables",
  "Cloudy with a Chance of Meatballs 2",
  "The Nutty Professor",
  "Jerry Maguire",
  "Bad Boys II",
  "Lilo & Stitch",
  "The Silence of the Lambs",
  "Grown Ups",
  "Neighbors",
  "The Firm",
  "We're the Millers",
  "Gran Torino",
  "10,000 BC",
  "American Gangster",
  "Epic",
  "Exodus: Gods and Kings",
  "Bambi",
  "The Princess and the Frog",
  "Batman Returns",
  "Indecent Proposal",
  "Something's Gotta Give",
  "Bridget Jones: The Edge of Reason",
  "The Incredible Hulk",
  "Waterworld",
  "The Truman Show",
  "Charlie's Angels",
  "The Fifth Element",
  "Parasite",
  "Jumanji",
  "Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan",
  "Robots",
  "Knight and Day",
  "Total Recall",
  "This Is It",
  "Terminator: Dark Fate",
  "The Lone Ranger",
  "Super 8",
  "Mojin: The Lost Legend",
  "Blade Runner 2049",
  "Charlie's Angels: Full Throttle",
  "Rush Hour 3",
  "The Full Monty",
  "Kung Fu Yoga",
  "Annabelle",
  "The Village",
  "Lost in Hong Kong",
  "Erin Brockovich",
  "Pegasus",
  "Get Out",
  "Marley & Me",
  "Halloween",
  "Us",
  "Cliffhanger",
  "Baahubali 2: The Conclusion",
  "Babe",
  "Men in Black: International",
  "Wild Hogs",
  "Encanto",
  "High School Musical 3: Senior Year",
  "Hercules",
  "X-Men: Dark Phoenix",
  "True Grit",
  "Bean",
  "American Hustle",
  "Enemy of the State",
  "You've Got Mail",
  "Eragon",
  "Brother Bear",
  "The Godfather",
  "The Mask of Zorro",
  "The Ring",
  "The Blair Witch Project",
  "Unbreakable",
  "Journey to the West: The Demons Strike Back",
  "Dumb and Dumber",
  "Glass",
  "Grown Ups 2",
  "The Peanuts Movie",
  "Rango",
  "Four Weddings and a Funeral",
  "Face/Off",
  "Teenage Mutant Ninja Turtles: Out of the Shadows",
  "Dark Shadows",
  "Dolittle",
  "Hulk",
  "Love Actually",
  "The Bravest",
  "Welcome to the Sticks",
  "Back to the Future Part III",
  "Pixels",
  "Rush Hour",
  "Journey to the Center of the Earth",
  "After Earth",
  "A Few Good Men",
  "Cloudy with a Chance of Meatballs",
  "8 Mile",
  "Daddy's Home",
  "RoboCop",
  "Eraser",
  "Alien: Covenant",
  "Sully",
  "Assassin's Creed",
  "Click",
  "Legend of Deification",
  "Resident Evil: Retribution",
  "Die Hard 2",
  "Crocodile Dundee II",
  "Planes",
  "Crazy Rich Asians",
  "Batman & Robin",
  "Downton Abbey",
  "Gulliver's Travels",
  "Gone in 60 Seconds",
  "Saturday Night Fever",
  "Silver Linings Playbook",
  "2 Fast 2 Furious",
  "Howl's Moving Castle",
  "Hidden Figures",
  "A.I. Artificial Intelligence",
  "Dead Poets Society",
  "Spy",
  "American Pie",
  "American Reunion",
  "Big Daddy",
  "Alvin and the Chipmunks: The Road Chip",
  "The Imitation Game",
  "Cruella",
  "The Day the Earth Stood Still",
  "American Wedding",
  "The Girl with the Dragon Tattoo",
  "Juno",
  "Argo",
  "Mr. Bean's Holiday",
  "The English Patient",
  "Sister Act",
  "Annabelle Comes Home",
  "Constantine",
  "Get Smart",
  "Space Jam",
  "Life Is Beautiful",
  "The Heat",
  "Ghost Rider",
  "Goodbye Mr. Loser",
  "Paddington 2",
  "Sleepless in Seattle",
  "Lethal Weapon 2",
  "The Green Hornet",
  "Out of Africa",
  "Youth",
  "Baby Driver",
  "Immortals",
  "Taken",
  "Percy Jackson & the Olympians: The Lightning Thief",
  "Hansel & Gretel: Witch Hunters",
  "Valerian and the City of a Thousand Planets",
  "Good Will Hunting",
  "Better Days",
  "Ford v Ferrari",
  "Jumper",
  "Elf",
  "The Social Network",
  "Chicken Run",
  "Con Air",
  "Interview with the Vampire: The Vampire Chronicles",
  "Flightplan",
  "Yes Man",
  "Non-Stop",
  "Honey, I Shrunk the Kids",
  "Fahrenheit 9/11",
  "Wild Wild West",
  "My Country, My Parents",
  "Geostorm",
  "Presumed Innocent",
  "Jungle Cruise",
  "Scary Movie 3",
  "Collateral",
  "Inferno",
  "Knocked Up",
  "Green Lantern",
  "What Happens in Vegas",
  "It's Complicated",
  "The Terminal",
  "Captain Phillips",
  "The Prince of Egypt",
  "Jack Reacher",
  "Kingdom of Heaven",
  "The Emoji Movie",
  "Too Cool to Kill",
  "Dracula Untold",
  "Central Intelligence",
  "Million Dollar Baby",
  "The Help",
  "Twins",
  "Little Women",
  "Valentine's Day",
  "Bad Teacher",
  "A Little Red Flower",
  "The Croods: A New Age",
  "Clear and Present Danger",
  "One Hundred and One Dalmatians",
  "Ted 2",
  "Bram Stoker's Dracula",
  "Vertical Limit",
  "Ghostbusters II",
  "The Patriot",
  "The Sorcerer's Apprentice",
  "Just Go with It",
  "The Expendables 3",
  "Dirty Dancing",
  "Creed II",
  "Smallfoot",
  "Public Enemies",
  "The Bourne Identity",
  "Disclosure",
  "Pulp Fiction",
  "The Aviator",
  "Crouching Tiger, Hidden Dragon",
  "Braveheart",
  "Into the Woods",
  "Bedtime Stories",
  "Miss Congeniality",
  "Entrapment",
  "Ace Ventura: When Nature Calls",
  "End of Days",
  "Bridget Jones's Baby",
  "Fury",
  "Battle Los Angeles",
  "Australia",
  "Due Date",
  "Master and Commander: The Far Side of the World",
  "A Series of Unfortunate Events",
  "The Little Mermaid",
  "Nice View",
  "District 9",
  "Moonraker",
  "The Others",
  "Horrible Bosses",
  "Us and Them",
  "Red Dragon",
  "Tomorrowland",
  "Me Before You",
  "Safe House",
  "S.W.A.T.",
  "The Fast and the Furious",
  "Traffic",
  "Paranormal Activity 3",
  "Philadelphia",
  "Sleepy Hollow",
  "The Holiday",
  "Raging Fire",
  "London Has Fallen",
  "The Break-Up",
  "Journey to the West",
  "JFK",
  "White House Down",
  "A Dog's Purpose",
  "Ponyo",
  "Fun with Dick and Jane",
  "Eat Pray Love",
  "You Don't Mess with the Zohan",
  "The Addams Family",
  "Hairspray",
  "King Arthur",
  "Yogi Bear",
  "Everest",
  "Vanilla Sky",
  "Arrival",
  "Need for Speed",
  "Garfield",
  "Patch Adams",
  "The Conjuring: The Devil Made Me Do It",
  "Kindergarten Cop",
  "Birds of Prey",
  "Straight Outta Compton",
  "21 Jump Street",
  "Valkyrie",
  "Open Season",
  "Cats & Dogs",
  "The Hunt for Red October",
  "Percy Jackson: Sea of Monsters",
  "Two Weeks Notice",
  "RED",
  "Shock Wave 2",
  "City of Angels",
  "The Pacifier",
  "50 First Dates",
  "The Island",
  "The Impossible",
  "Lost in Thailand",
  "Christopher Robin",
  "Jack the Giant Slayer",
  "Ghostbusters: Afterlife",
  "Smurfs: The Lost Village",
  "Chinese Doctors",
  "Spy Kids 3: Game Over",
  "Panic Room",
  "The Other Woman",
  "Stargate",
  "Beowulf",
  "The Vow",
  "Anger Management",
  "Tropic Thunder",
  "The Shape of Water",
  "Rocketman",
  "The Pelican Brief",
  "The BFG",
  "The Intern",
  "Wallace & Gromit: The Curse of the Were-Rabbit",
  "Gnomeo & Juliet",
  "Weathering with You",
  "The Sum of All Fears",
  "Gangs of New York",
  "The Monkey King 2",
  "Paranormal Activity",
  "The Lego Movie 2: The Second Part",
  "The Equalizer",
  "Sheep Without a Shepherd",
  "The Longest Yard",
  "The Santa Clause",
  "Cheaper by the Dozen",
  "The Equalizer 2",
  "Hollow Man",
  "Outbreak",
  "The White Storm 2: Drug Lords",
  "The X Files",
  "Breakup Buddies",
  "Rambo III",
  "The Secret Life of Walter Mitty",
  "Project Gutenberg",
  "Jaws 2",
  "12 Years a Slave",
  "Heat",
  "Mr. Popper's Penguins",
  "The Grudge",
  "I Now Pronounce You Chuck & Larry",
  "The Horse Whisperer",
  "Walk the Line",
  "Jian Bing Man",
  "The Jungle Book 2",
  "The Final Destination",
  "Atlantis: The Lost Empire",
  "Inside Man",
  "The Waterboy",
  "Hugo",
  "Pitch Perfect 3",
  "Watchmen",
  "The Birdcage",
  "Moulin Rouge!",
  "Snow White and the Seven Dwarfs",
  "Hop",
  "Bad Moms",
  "Jupiter Ascending",
  "Knowing",
  "102 Dalmatians",
  "Storks",
  "Stand by Me Doraemon",
  "Paul Blart: Mall Cop",
  "Wayne's World",
  "Maverick",
  "Mirror Mirror",
  "The Man in the Iron Mask",
  "Cape Fear",
  "The Haunted Mansion",
  "The Monkey King Havoc in Heavens Palace",
  "While You Were Sleeping",
  "The Bridges of Madison County",
  "Poseidon",
  "The First Wives Club",
  "Cliff Walkers",
  "Scooby-Doo 2: Monsters Unleashed",
  "Hot Shots!",
  "Road to Perdition",
  "Kill Bill: Vol. 1",
  "Abominable",
  "The Scorpion King",
  "Sweet Home Alabama",
  "Daddy's Home 2",
  "Hacksaw Ridge",
  "Deja Vu",
  "The Post",
  "Dangerous Minds",
  "The Dictator",
  "The League of Extraordinary Gentlemen",
  "Allegiant",
  "Daredevil",
  "City Slickers",
  "He's Just Not That Into You",
  "Eagle Eye",
  "Along Came Polly",
  "Flushed Away",
  "Scary Movie 4",
  "Dante's Peak",
  "Brokeback Mountain",
  "Patriot Games",
  "Flubber",
  "Baywatch",
  "Double Jeopardy",
  "War Horse",
  "Paranormal Activity 2",
  "How to Lose a Guy in 10 Days",
  "Alien vs. Predator",
  "Hero",
  "The 40-Year-Old Virgin",
  "Lee Daniels' The Butler",
  "The Haunting",
  "The Descendants",
  "The A-Team",
  "Tootsie",
  "In the Line of Fire",
  "Analyze This",
  "The Hitman's Bodyguard",
  "Looper",
  "Serial (Bad) Weddings",
  "Ip Man 4: The Finale",
  "Dr. Dolittle 2",
  "The Italian Job",
  "The Bucket List",
  "Sleeping with the Enemy",
  "Cowboys & Aliens",
  "The Mule",
  "George of the Jungle",
  "Evan Almighty",
  "Amélie",
};